package com.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dept.id
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_dept.dept_name
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dept.id
     *
     * @return the value of table_dept.id
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dept.id
     *
     * @param id the value for table_dept.id
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_dept.dept_name
     *
     * @return the value of table_dept.dept_name
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_dept.dept_name
     *
     * @param deptName the value for table_dept.dept_name
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}