package com.project.smart_campus.pojo;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.id
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.name
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_test.pwd
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    private Integer pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.id
     *
     * @return the value of tb_test.id
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.id
     *
     * @param id the value for tb_test.id
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.name
     *
     * @return the value of tb_test.name
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.name
     *
     * @param name the value for tb_test.name
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.pwd
     *
     * @return the value of tb_test.pwd
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    public Integer getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.pwd
     *
     * @param pwd the value for tb_test.pwd
     *
     * @mbggenerated Wed Jul 26 21:23:04 CST 2023
     */
    public void setPwd(Integer pwd) {
        this.pwd = pwd;
    }
}