package com.mybatis.mapper;

import com.mybatis.pojo.Emp;
import java.util.List;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_emp
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_emp
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_emp
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    Emp selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_emp
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    List<Emp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_emp
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    int updateByPrimaryKey(Emp record);
}