package com.mybatis.mapper;

import com.mybatis.pojo.Dept;
import java.util.List;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dept
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dept
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dept
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    Dept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dept
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_dept
     *
     * @mbggenerated Mon Jul 24 16:29:14 CST 2023
     */
    int updateByPrimaryKey(Dept record);
}