package com.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_emp.eid
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    private Integer eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_emp.emp_name
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_emp.age
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_emp.sex
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_emp.email
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_emp.id
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_emp.eid
     *
     * @return the value of table_emp.eid
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_emp.eid
     *
     * @param eid the value for table_emp.eid
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_emp.emp_name
     *
     * @return the value of table_emp.emp_name
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_emp.emp_name
     *
     * @param empName the value for table_emp.emp_name
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_emp.age
     *
     * @return the value of table_emp.age
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_emp.age
     *
     * @param age the value for table_emp.age
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_emp.sex
     *
     * @return the value of table_emp.sex
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_emp.sex
     *
     * @param sex the value for table_emp.sex
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_emp.email
     *
     * @return the value of table_emp.email
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_emp.email
     *
     * @param email the value for table_emp.email
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_emp.id
     *
     * @return the value of table_emp.id
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_emp.id
     *
     * @param id the value for table_emp.id
     *
     * @mbggenerated Mon Jul 24 17:15:17 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Emp() {
    }

    public Emp(Integer eid, String empName, Integer age, String sex, String email, Integer id) {
        this.eid = eid;
        this.empName = empName;
        this.age = age;
        this.sex = sex;
        this.email = email;
        this.id = id;
    }
}